### ISSUE TITLE
Failed to initialize video producer (Error code 4099)

### ISSUE THREAD

**Issue by adithyamurali** [aws-robotics/kinesisvideo-ros1#16]
Hi guys,

I'm trying to connect my camera to Kinesis and I'm facing the following error when I start the kinesis_video_streamer with my config file:

`[FATAL] [1550936504.944780017]: [Initialize] Failed to initialize video producer. Error code: 4099`

However, I'm able to echo hz the topic publishing the encoded data from my camera using the h264_video_encoder. I used the apt-get installation.

Thanks

**Comment by juanrh** [comment]
Hi Adithya, 

Thanks for taking a look to our Kinesis Video node. This looks like the same problem we had on #2. The fix for that bug is not released yet on Apt. Would you mind trying building from source using the [branch release-v1](https://github.com/aws-robotics/kinesisvideo-ros1/tree/release-v1)?

Thanks

**Comment by adithyamurali** [comment]
Thanks @juanrh That worked.

**Comment by AAlon** [comment]
Sync completed, the fixed version is available in apt.
