### ISSUE TITLE
Poor image color quality

### ISSUE THREAD

**Issue by nburek** [aws-robotics/kinesisvideo-ros1#24]
We have a report from a user that they are seeing very poor image color quality when streaming to Kinesis Video Service from a Turtlebot 3. 

![KVS Working](https://user-images.githubusercontent.com/312272/56062499-6cab9980-5d21-11e9-85f4-30737520d6d2.png)

**Comment by juanrh** [comment]
Hi,

Thanks for bringing this to our attention.  @MacInnis can you please indicate which OS, board, camera version, and ROS version it's being used? If this is the same as in [this issue for the person detection sample application](https://github.com/aws-robotics/aws-robomaker-sample-application-persondetection/issues/22), then I suggest trying with Ubuntu Xenial and the instructions and launch file provided there, to see if that improves the image quality. I used that setting on a TurtleBot 3 Burger running Ubuntu Xenial and ROS Kinetic and I had no color issues in Kinesis Video Streams. 

If can you still have issues, can you please attach the launch files and configuration files in the workspace so we can reproduce the issue? That would be the directories `workspace/opt/built_workspace/person_detection_robot/share/person_detection_robot/launch` and `workspace/opt/built_workspace/person_detection_robot/share/person_detection_robot/config` that are contained in the file `workspace.tar.gz` that is part of the robot_ws bundle. 

Thanks

**Comment by ross-desmond** [comment]
@nburek Is this still an issue after the suggestions from @juanrh?

**Comment by timrobotson** [comment]
I tested the latest version of the [Person Detection Sample Application](https://github.com/aws-robotics/aws-robomaker-sample-application-persondetection) with the following setup:

- Turtlebot Waffle Pi 
- Raspberry Pi B
- Raspicam
- Ubuntu 16.04
- ROS Kinetic
- Resolution: 410x308

Using `master` branch of kinesisvideo-ros1 and running with the updated instructions/config in https://github.com/aws-robotics/aws-robomaker-sample-application-persondetection/pull/25 and image color quality was good. 

![2019-05-23-183454_1623x872_scrot](https://user-images.githubusercontent.com/38477849/58296808-29b1fc80-7d8a-11e9-8158-9991535edd54.png)

It may have been because your resolution was set to 640 x 480 and so it was trying to stretch the image which caused the distortion. The default resolution was changed to 410x308 in the [aforementioned PR](https://github.com/aws-robotics/aws-robomaker-sample-application-persondetection/pull/25) as that is the correct resolution for our camera (the default one that comes with a turtlebot). There are other Rasberry Pi cameras that have different resolutions though so 640x480 may be correct for yours.
