### ISSUE TITLE
Using compressed image

### ISSUE THREAD

**Issue by Gil401** [aws-robotics/kinesisvideo-ros1#27]
Hi Guys,

A quick question.
Is there a way to stream the video using a compressed image (sensor_msgs/CompressedImage)?

Thanks

**Comment by ross-desmond** [comment]
Hi @Gil401,

Thank you for you question!

Does this mean that you already have a camera node which is producing a compressed image (sensor_msgs/CompressedImage)?
If so you will need to launch with image_transport set to compressed when launching [h264_video_encode](https://github.com/aws-robotics/kinesisvideo-encoder-ros1/blob/master/h264_video_encoder/launch/h264_video_encoder.launch#L18). This will use the [compressed_image_transport](http://wiki.ros.org/compressed_image_transport) and subscribe to the compressed image topic. By default the encoder node should use sensor_msgs/CompressedImage. Also it is required to use the encoder node with kinesis_video_streamer since the Kinesis requires h264 encoding.

Does this help?

**Comment by Gil401** [comment]
it works.
Thanks.
