### ISSUE TITLE
Why the image is weird ?

### ISSUE THREAD

**Issue by ngthanhtin** [aws-robotics/kinesisvideo-ros1#42]
Hello, I tried to publish image from local bot to aws but the result on the aws is that:
![Screenshot from 2020-04-15 17-15-53](https://user-images.githubusercontent.com/17596799/79438264-8438f480-7ffd-11ea-8778-ff5307359250.png)
 The screen after I run roslaunch kinesis_video_streamer sample_application.launch:

![Screenshot from 2020-04-16 16-17-15](https://user-images.githubusercontent.com/17596799/79438492-c6623600-7ffd-11ea-8f80-b3576098bb5f.png)

**Comment by raghaprasad** [comment]
@ngthanhtin Thanks for reaching out. 
Can you give some more details regarding your environment? 
Please list out the following:
- Version of ubuntu
- Version of ROS package you are using
- ROS1 version (Kinetic / Melodic) ? 
And any other relevant information that you can give.

**Comment by ngthanhtin** [comment]
I used ubuntu 18.04, ros1 melodic. Maybe I used a super cam on my bot so it displayed weird colors on the aws.

**Comment by mm318** [comment]
Hi @ngthanhtin,

I am not sure what is a super cam. Can you describe in more detail what are the hardware specifications of your robot (including CPU, RAM, etc.)?

What I noticed in the screenshot of the log messages that are showing that in your hardware configuration, the encoder node needed to fallback to using a software encoder, instead of a hardware-accelerated encoder. This can bog down a robot system and the encoded stream that ultimately ends up reaching the Kinesis service could be missing data. Did you notice if the framerate of the stream that you saw on the AWS Kinesis console is also very low?
